name: drivepod

services:
  drivepod:
    build: .
    image: drivepod
    container_name: drivepod
    restart: unless-stopped
    ports:
      - "24320:80"
    volumes:
      - ./data:/app/data
      - ./cache:/var/www/cache
    environment:
      - NODE_ENV=production