name: drivepod

services:
  drivepod:
    build: .
    image: drivepod
    container_name: drivepod
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "24320:80"
    volumes:
      - /mnt/e/projects/drivepod/data:/mnt/e/projects/drivepod/data
      - /mnt/e/projects/drivepod/cache:/mnt/e/projects/drivepod/cache
    env_file:
      - .env
    environment:
      - NODE_ENV=production
